### ISSUE TITLE
Curriculum tables are non responsive

### ISSUE THREAD

**Issue by ju5tu5** [CMDA/brightspace#14]
The curriculum tables do not scale due to large text content and force a larger than screen width on mobile phones for all content on the page.

**Comment by ju5tu5** [comment]
We might hide the first column on mobile as they are all <th> elements and the information is less important than the links to the actual courses. We should also shrink the font-size a bit to make it fit.

**Comment by joostf** [comment]
Fixed with a scrollable container (.scrollable) around the table. I think it's still a good idea to hide the first column though..
