### ISSUE TITLE
link naar SRP Fundament

### ISSUE THREAD

**Issue by britwijnmaalen** [CMDA/brightspace#18]
Kunnen jullie de links van uit de vakkenplaatjes van Professionalising/SPR op de P-pagina linken naar de pagina van SRP Fundament?

**Comment by joostf** [comment]
Aangepast

**Comment by britwijnmaalen** [comment]
top!

groet van
Brit

[—]

On 8 Oct 2019, at 15:45, Joost <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #18<https://github.com/CMDA/brightspace/issues/18>.
