### ISSUE TITLE
CMD logo branding

### ISSUE THREAD

**Issue by dandevri** [CMDA/brightspace#5]
In de vorige brand guide kon je die blokken van CMD niet naast elkaar zetten, ik zie dat in de [versie van`juli 2018`](https://moodle.cmd.hva.nl/pluginfile.php/62051/mod_resource/content/2/CMD%20beeldtaal%20manual.pdf) niet expliciet staan dus nu mag het weer wel? ¯\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/22084444/60670439-e8286d00-9e70-11e9-983f-81906b9f3f86.png)

Moeten er sws nog een CMD sausje overheen of willen we het meer ah la brightspace?

**Comment by joostf** [comment]
We gaan eerst de html er in zetten, vooralsnog is er alleen wat basis styling toegepast. Als de HTML staat kunnen we kijken hoe we de huisstijl kunnen toepassen op zo'n manier dat het er binnen Brightspace netjes uitziet!

**Comment by ju5tu5** [comment]
Sterker nog, de bovenbalk wordt helemaal weggehaald, branding is niet nodig omdat de pagina onder de brightspace header wordt ingeladen. It's not a page.. it's a sub..
