### ISSUE TITLE
Informatie pagina's

### ISSUE THREAD

**Issue by joostf** [CMDA/brightspace#7]

**Comment by joostf** [comment]
- [x] docenten (JS)
- [x] extrauitdaging (JF)
- [x] faciliteiten (JF)
- [x] icons (JF)
- [x] internationaal (JS)
- [x] locaties (JF)
- [x] startstudiejaar
- [x] studiekeuzecheck
- [x] wiewatwaar (JF)

**Comment by ju5tu5** [comment]
Checked
